
wandb:
  project: "uxnet-semantic-seg"
  run_name: "soft_masked"

training:
  seed: 1234
  current_checkpoint: "./checkpoints/final_model_cubes.pth"
  prefetch_factor: 1
  persistent_workers: True
  ema_beta: 0.998
  num_epochs: 30
  scheduler_epochs: 200
  epoch_size: 100
  batch_size: 4
  workers: 16
  amp: True
  warmup_factor: 1
  lr: 0.001
  min_lr: 0.000001
  weight_decay: 0.00001
  max_grad_norm: 3
  synthetic_ratio: 0.4
  boundary_alpha: 1
  
model:
  in_channels: 1
  out_channels: 1
  channels: [64, 128, 320, 512, 768, 1024]
  strides: [4, 2, 2, 2, 2]
  kernel_size: [7, 3, 3, 3, 3]


data:
  input_file: "/mnt/localdisk/giorgio/scroll1-hdf5/20230205180739.b2nd"
  label_file: "/home/giorgio/scrolls/scroll1/volumes/labels/labels.b2nd"
  synth_input_folder: "/home/giorgio/Projects/AesFA/output/train"
  synth_label_folder: "/home/giorgio/Projects/AesFA/labels"
  block_size: [256, 256, 256]
  #block_size: [512,512,512]

distributed:
  world_size: 8
  master_addr: "localhost"
  master_port: "12355"

inference:
  seed: 42
  #weights_path: './checkpoints/140724_epoch_20.pth'
  weights_path: './checkpoints/160724_uxnet_mask_epoch_28.pth'
  output_dir: './uxnet_mask_160724_0.5/'
  max_chunk_size: 1024
  #batch_size: 64
  batch_size: 2
  threshold: 0.5