
wandb:
  project: "uxnet-semantic-seg"
  run_name: "soft_masked"

training:
  seed: 1891 #1234
  current_checkpoint: "/app/scrolls/giorgio/unet/checkpoints/160724_uxnet_mask_epoch_28.pth" #uxnet_mask_epoch_18, 28 (non,mask:44)
  prefetch_factor: 4 #4
  persistent_workers: True
  ema: False
  ema_beta: 0.999
  ema_step: 10
  num_epochs: 100
  scheduler_epochs: 100
  #scheduler_epochs: 100 hyperstrict
  epoch_size: 24
  batch_size: 4 #6 #12
  workers: 16 # 16
  amp: True
  warmup_epochs: 5
  lr : 0.001
  #lr: 0.0001 
  #lr: 0.00001 hyperstrict
  min_lr: 0.000001
  weight_decay: 0.00001
  max_grad_norm: 10
  synthetic_ratio: 0.4
  boundary_alpha: 1
  cube_size: 128


data:
  input_file: "/mnt/localdisk/giorgio/scroll1-hdf5/20230205180739.b2nd"
  label_file: "/home/giorgio/scrolls/scroll1/volumes/labels/labels.b2nd"
  synth_input_folder: "/home/giorgio/Projects/AesFA/output/train"
  synth_label_folder: "/home/giorgio/Projects/AesFA/labels"
  block_size: [256, 256, 256]
  #block_size: [512,512,512]

distributed:
  world_size: 8
  master_addr: "localhost"
  master_port: "12355"

inference:
  seed: 42
  weights_path: './checkpoints/160724_uxnet_mask_epoch_28.pth'
  output_dir: './uxnet_mask_160724_0.5/'
  max_chunk_size: 1024
  #batch_size: 64
  batch_size: 2
  threshold: 0.5